-- =============================================================
-- MODULE 20: Compliance Calendar — Schema
-- =============================================================
-- Design principles:
--   • compliance_obligation_types is a shared lookup (no org scope)
--     — seeded with Legislation, Standard, Permit/Licence Condition,
--       Internal Policy.
--   • compliance_obligations are the master registry of recurring
--     obligations (legal, permit, licence, policy). Each obligation
--     records its frequency and next due date; a trigger or scheduler
--     generates compliance_tasks from it.
--   • compliance_tasks are the individual calendar items produced
--     from an obligation for a specific due date.  They carry
--     assignment, evidence and completion tracking.
--   • task_number is generated via reference_counters (prefix COMP).
--
-- Tables (3):
--   compliance_obligation_types  — lookup: Legislation, Standard, etc.
--   compliance_obligations       — org-scoped obligation registry
--   compliance_tasks             — individual due-date task instances
-- =============================================================

-- =============================================================
-- COMPLIANCE OBLIGATION TYPES  (shared lookup, no org scope)
-- =============================================================
CREATE TABLE IF NOT EXISTS compliance_obligation_types (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT        NOT NULL UNIQUE,
  colour_code   TEXT        NOT NULL DEFAULT '#525252',
  display_order INT                  DEFAULT 0
);

-- =============================================================
-- COMPLIANCE OBLIGATIONS
-- Master registry of recurring compliance requirements.
-- frequency drives how often a new task should be spawned.
-- next_due_date is the next calendar date a task is due.
-- is_critical flags obligations whose breach is high-severity.
-- =============================================================
CREATE TABLE IF NOT EXISTS compliance_obligations (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organisation_id     UUID        NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  title               TEXT        NOT NULL,
  description         TEXT,
  obligation_type_id  UUID        REFERENCES compliance_obligation_types(id),
  regulatory_body     TEXT,
  standard_reference  TEXT,
  site_id             UUID        REFERENCES sites(id),
  frequency           TEXT                 DEFAULT 'annual'
                                  CHECK (frequency IN (
                                    'one_time','daily','weekly','monthly',
                                    'quarterly','semi_annual','annual','biennial'
                                  )),
  next_due_date       DATE,
  owner_id            UUID        REFERENCES user_profiles(id),
  status              TEXT        NOT NULL DEFAULT 'active'
                                  CHECK (status IN ('active','inactive','superseded')),
  is_critical         BOOLEAN              DEFAULT false,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by          UUID        REFERENCES user_profiles(id)
);

-- =============================================================
-- COMPLIANCE TASKS
-- Individual calendar task instances spawned from an obligation.
-- task_number generated by trigger (prefix COMP, counter per org).
-- evidence_notes allows inline evidence capture without a file upload.
-- =============================================================
CREATE TABLE IF NOT EXISTS compliance_tasks (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  obligation_id   UUID        NOT NULL REFERENCES compliance_obligations(id) ON DELETE CASCADE,
  organisation_id UUID        NOT NULL REFERENCES organisations(id),
  task_number     TEXT,
  title           TEXT        NOT NULL,
  description     TEXT,
  due_date        DATE        NOT NULL,
  assigned_to     UUID        REFERENCES user_profiles(id),
  status          TEXT        NOT NULL DEFAULT 'pending'
                              CHECK (status IN (
                                'pending','in_progress','completed','overdue','cancelled'
                              )),
  completed_at    TIMESTAMPTZ,
  completed_by    UUID        REFERENCES user_profiles(id),
  evidence_notes  TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by      UUID        REFERENCES user_profiles(id)
);

-- =============================================================
-- INDEXES
-- =============================================================
CREATE INDEX IF NOT EXISTS idx_comp_oblig_org        ON compliance_obligations(organisation_id, status);
CREATE INDEX IF NOT EXISTS idx_comp_oblig_due        ON compliance_obligations(next_due_date) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_comp_oblig_owner      ON compliance_obligations(owner_id);
CREATE INDEX IF NOT EXISTS idx_comp_task_org         ON compliance_tasks(organisation_id, status);
CREATE INDEX IF NOT EXISTS idx_comp_task_due         ON compliance_tasks(due_date, status);
CREATE INDEX IF NOT EXISTS idx_comp_task_obligation  ON compliance_tasks(obligation_id);
CREATE INDEX IF NOT EXISTS idx_comp_task_assigned    ON compliance_tasks(assigned_to);
