-- Gap 5: Seed 25 system risk templates
INSERT INTO risks (organisation_id, is_template, template_industry, title, category, hazard_description, people_at_risk, inherent_likelihood, inherent_consequence, inherent_risk_level, inherent_risk_score, controls_description, residual_likelihood, residual_consequence, residual_risk_level, residual_risk_score, status)
VALUES
-- GENERAL (7 risks)
(NULL, true, 'general', 'Manual Handling - Lifting and Carrying', 'Ergonomic', 'Workers lifting or carrying heavy or awkward loads may suffer musculoskeletal injuries including back strain, shoulder injuries, and hernias.', 'All workers performing physical tasks', 3, 3, 'medium', 9, 'Training on safe lifting techniques. Use of mechanical aids (trolleys, forklifts) for loads >15kg. Team lifting for loads >25kg. Regular task rotation.', 2, 2, 'low', 4),
(NULL, true, 'general', 'Slip, Trip and Fall - Same Level', 'Physical', 'Workers walking on wet, slippery, uneven, or cluttered surfaces may slip, trip or fall causing soft tissue injuries, fractures, or head injuries.', 'All personnel on site', 3, 2, 'medium', 6, 'Good housekeeping procedures. Non-slip flooring and footwear. Spill clean-up procedures. Adequate lighting. Regular inspections.', 2, 2, 'low', 4),
(NULL, true, 'general', 'Electrical Hazards - General', 'Electrical', 'Contact with live electrical equipment, damaged wiring, or overloaded circuits may cause electric shock, burns, cardiac arrest, or fire.', 'All workers, maintenance staff, electricians', 2, 5, 'high', 10, 'Qualified electricians only for electrical work. Lockout/tagout procedures. Regular inspection and testing of equipment. RCD protection. No DIY electrical repairs.', 1, 4, 'medium', 4),
(NULL, true, 'general', 'Chemical Exposure - Hazardous Substances', 'Chemical', 'Inhalation, skin contact, or ingestion of hazardous chemicals (cleaning agents, solvents, paints) may cause acute or chronic health effects.', 'Workers using or near chemicals', 3, 3, 'medium', 9, 'SDS available for all chemicals. Appropriate PPE (gloves, goggles, respirator). Adequate ventilation. Substitution with less hazardous alternatives where possible.', 2, 2, 'low', 4),
(NULL, true, 'general', 'Fire and Explosion Risk', 'Fire', 'Ignition of flammable materials, gas leaks, or electrical faults may cause fire or explosion resulting in burns, smoke inhalation, or fatalities.', 'All site personnel', 2, 5, 'high', 10, 'Fire detection and suppression systems. No smoking policy. Proper storage of flammables. Emergency evacuation plan and drills. Regular fire equipment inspections.', 1, 4, 'medium', 4),
(NULL, true, 'general', 'Working at Heights (General)', 'Physical', 'Falls from ladders, platforms, roofs, or elevated work areas may cause serious injury or death.', 'Workers performing tasks above 2 metres', 2, 5, 'high', 10, 'Fall prevention hierarchy: eliminate task at height, use scaffolding, use EWP, use safety nets, use harness. Regular equipment inspection. Competency training. Edge protection.', 1, 4, 'medium', 4),
(NULL, true, 'general', 'Fatigue and Mental Health', 'Psychosocial', 'Excessive working hours, shift work, high workload, or workplace stress may lead to fatigue, burnout, and mental health conditions affecting safety and performance.', 'All workers, especially shift workers and managers', 3, 3, 'medium', 9, 'Maximum hours and shift rotation policy. Fatigue management training. Mental health first aiders. Employee Assistance Program. Regular workload reviews.', 2, 2, 'low', 4),

-- CONSTRUCTION (5 risks)
(NULL, true, 'construction', 'Excavation and Trenching Collapse', 'Physical', 'Unsupported excavations or trenches may collapse, burying workers and causing crush injuries or asphyxiation.', 'Workers in or near excavations', 2, 5, 'high', 10, 'Competent person inspection before entry. Shoring, battering, or benching for trenches >1.5m. No entry without authorisation. Spoil placed minimum 0.6m from edge. Emergency rescue plan.', 1, 5, 'high', 5),
(NULL, true, 'construction', 'Struck by Falling Objects', 'Physical', 'Tools, materials, or debris dropped from heights may strike workers below causing head injuries, fractures, or fatalities.', 'Workers below elevated work areas, pedestrians', 3, 4, 'high', 12, 'Exclusion zones below elevated work. Toe boards on scaffolding. Tool lanyards. Hard hat requirement. Netting and catch platforms. Tool boxes at height.', 2, 3, 'medium', 6),
(NULL, true, 'construction', 'Plant and Heavy Equipment', 'Physical', 'Contact with moving plant (excavators, forklifts, trucks) may cause crush injuries, amputations, or fatalities.', 'Workers and pedestrians near plant', 2, 5, 'high', 10, 'Traffic management plan. Segregation of plant and pedestrian areas. Spotters for reversing. Exclusion zones. Competency checks for operators. Pre-start inspections.', 1, 5, 'high', 5),
(NULL, true, 'construction', 'Confined Space Entry', 'Physical', 'Entering confined spaces (pits, tanks, sewers) without proper controls may expose workers to toxic atmospheres, oxygen deficiency, or engulfment.', 'Workers required to enter confined spaces', 1, 5, 'high', 5, 'Confined space permit system. Atmospheric testing before and during entry. Trained standby person. Rescue equipment on site. Mechanical ventilation. Communication systems.', 1, 4, 'medium', 4),
(NULL, true, 'construction', 'Noise-Induced Hearing Loss', 'Physical', 'Prolonged exposure to high noise levels from power tools, machinery, and compressors may cause permanent hearing damage.', 'All workers on construction sites', 4, 2, 'medium', 8, 'Noise assessment. Engineering controls (quieter equipment, enclosures). Administrative controls (rotation, scheduling). Hearing protection zones. Audiometric testing program.', 2, 2, 'low', 4),

-- RETAIL (5 risks)
(NULL, true, 'retail', 'Customer Aggression and Violence', 'Psychosocial', 'Verbal abuse, threats, or physical assault from customers may cause psychological harm and physical injury to staff.', 'Customer-facing staff, especially lone workers', 3, 3, 'medium', 9, 'De-escalation training. Duress alarms and CCTV. Clear aggression policy. Incident reporting system. Support for affected staff (EAP). Security personnel at high-risk times.', 2, 2, 'low', 4),
(NULL, true, 'retail', 'Lone Worker Safety', 'Physical', 'Staff working alone (opening/closing, after hours, delivery acceptance) face increased risk with no immediate assistance available.', 'Staff working alone or in isolated areas', 3, 3, 'medium', 9, 'Lone worker check-in procedures. Personal duress devices. Time-based check-ins with manager. Clear emergency contact procedures. No lone working after hours where possible.', 2, 2, 'low', 4),
(NULL, true, 'retail', 'Manual Handling - Stock and Deliveries', 'Ergonomic', 'Unloading deliveries, stacking shelves, and moving stock may cause musculoskeletal injuries especially to the back, shoulders, and wrists.', 'Warehouse and shop floor staff', 3, 3, 'medium', 9, 'Training on safe lifting. Mechanical aids (trolleys, pallet jacks). Team lifting for heavy items. Shelf height limits. Regular rotation of physically demanding tasks.', 2, 2, 'low', 4),
(NULL, true, 'retail', 'Cash Handling and Robbery', 'Psychosocial', 'Handling cash at registers or during banking runs creates risk of robbery, which may result in physical harm and significant psychological trauma.', 'Cashiers, managers handling cash', 2, 4, 'high', 8, 'Minimise cash on site (electronic payments). Time-delay safes. No set routine for banking. CCTV coverage. Staff not to resist robbery. Post-incident counselling available.', 1, 4, 'medium', 4),
(NULL, true, 'retail', 'Slips in Retail Environment', 'Physical', 'Spills of liquids or produce on retail floors may cause customer and staff slip injuries.', 'All staff and customers', 4, 2, 'medium', 8, 'Immediate spill clean-up and wet floor signage. Non-slip matting at entrances. Regular floor inspections. Non-slip footwear requirement for staff. Clear reporting procedure.', 2, 2, 'low', 4),

-- FOOD SERVICE (5 risks)
(NULL, true, 'food_service', 'Burns from Hot Surfaces and Equipment', 'Physical', 'Contact with hot cooking equipment, surfaces, oils, and steam may cause burns ranging from minor to severe.', 'Kitchen staff, food preparation workers', 4, 3, 'high', 12, 'Oven mitts and heat-resistant gloves. Warning labels on hot surfaces. Staff training on burn first aid. Appropriate PPE. Equipment guards and cool-down procedures.', 2, 2, 'low', 4),
(NULL, true, 'food_service', 'Cuts from Knives and Sharp Equipment', 'Physical', 'Use of knives, slicers, mandolins, and graters creates risk of lacerations and puncture wounds.', 'Kitchen and food prep staff', 4, 2, 'medium', 8, 'Cut-resistant gloves for high-risk tasks. Knife safety training. Secure knife storage. Safe blade disposal procedures. First aid equipment nearby.', 2, 2, 'low', 4),
(NULL, true, 'food_service', 'Food Allergen Cross-Contamination', 'Chemical', 'Cross-contamination of allergens (nuts, gluten, dairy, eggs) may cause severe allergic reactions including anaphylaxis in customers.', 'Customers with allergies, kitchen staff', 2, 5, 'high', 10, 'Allergen training for all staff. Separate equipment for allergen-free meals. Clear menu labelling. Customer allergy declaration process. Epinephrine auto-injectors on site. Supplier allergen declarations.', 1, 4, 'medium', 4),
(NULL, true, 'food_service', 'Slippery Kitchen Floors', 'Physical', 'Spills of oils, water, and food waste on kitchen floors create high slip risk for staff in a fast-paced environment.', 'Kitchen staff', 4, 3, 'high', 12, 'Non-slip flooring. Non-slip footwear requirement. Immediate clean-up of spills. Floor drainage. Regular mopping schedule. Wet floor signs.', 2, 2, 'low', 4),
(NULL, true, 'food_service', 'Cold Room Entrapment', 'Physical', 'Staff entering cold storage rooms may become entrapped if the door mechanism fails, leading to hypothermia or death.', 'Staff accessing cold and freezer rooms', 1, 5, 'high', 5, 'Interior emergency release on all cold room doors. Buddy system for cold room access. Regular door mechanism inspections. Communication device inside cold rooms. Emergency alarm button.', 1, 3, 'medium', 3);
